# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:latest

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt-get update && apt-get install -y libicu-dev libgmime-2.6-dev qt5-default
          - for i in connectivity export-messages extract-msgid extract-msgmeta filter-newsgroups filter-spam import-source-mbox import-source-slrnpull import-source-slrnpull-7z kill-duplicates lexdist lexhash lexicon lexopt lexsort lexstats merge-raw package query query-raw relative-complement repack-lz4 repack-zstd threadify utf8ize ; do make -j8 -C $i/build/unix ; done
          - cd browser && qmake && make -j8
